name: grpc_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:

  grpc: ^3.0.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
