name: grpc_client
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  grpc: ^3.0.0
  protobuf: ^2.0.0
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
